name: Build and Test Package
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: macos-10.15
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Xcode 12
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.4'

      - name: Export macOS SDK
        run: echo SDKROOT=$(xcrun --sdk macosx --show-sdk-path) >> $GITHUB_ENV
      
      - name: Install gem dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      
      - name: Cache cocoapods dependencies
        uses: actions/cache@v2
        id: cache-pods
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-pods-
      
      - name: Install cocoapods dependencies  
        if: steps.cache-pods.outputs.cache-hit != 'true'
        run: bundle exec pod install
      
      - name: Build Swift Package
        run: swift build -j 2 --disable-index-store -v

      - name: Test Framework on iOS and tvOS
        run: bundle exec fastlane ios test ci:github
      
      - name: Test Framework on macOS
        run: bundle exec fastlane mac test ci:github
      
      - name: Lint podspec
        run: bundle exec pod lib lint
